title: "Le Séquenceur"
description: "Association des Musiques Numériques & Innovantes"
lang: fr

liquid:
  error_mode: strict

kramdown:
  show_warnings: true

exclude:
  - Makefile
  - selection.json

plugins:
  - jekyll-feed
  - jekyll-tidy
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: "/:year/:month/:day/:title/"
future: true

collections:
  projects:
    output: true
    permalink: projets/:title/
